### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by weppos** [jodosha/minegems#10]
Hard task: we need to find a name. :D

I love the minegems internal name, we can continue to use it. However, we might probably need a new name and domain to release the product.

I strongly encourage to try to find a name with an associated .COM domain. We should try to avoid bizarre combinations or using strange TLD for two reasons:
1. They are temporary trends (think about something-fu, act_as...). Yesterday was .ly, today is .io and tomorrow another one.
2. They are risky.

I believe the `gem` word should be clearly contained in the name.

**Comment by weppos** [comment]
`gemforge.com` will expire on March, but I doubt it will be released.

```
Updated Date: 12-jan-2011
Creation Date: 04-mar-2007
Expiration Date: 04-mar-2012
```

**Comment by weppos** [comment]
gemarmory.com is AVAILABLE. (gem + armory)

**Comment by jodosha** [comment]
what about gemvault? The `.com` isn't available, it's just a possible name.

**Comment by weppos** [comment]
Not bad. It's a pity for `gemvault.com`.
