### ISSUE TITLE
MINEGEMS_SITE vs request.subdomain

### ISSUE THREAD

**Issue by weppos** [jodosha/minegems#13]
Any reason for using a custom `MINEGEMS_SITE` environment variable instead of relying on `request.subdomain` feature?
http://railscasts.com/episodes/221-subdomains-in-rails-3

**Comment by jodosha** [comment]
Because that's an Hash with all the informations about the subsite.
Example:

```
GET http://acme.minege.ms
request.subdomain         # => 'acme'
env['MINEGEMS_SITE'] # => { tld: 'acme', name: 'Acme Inc.' } etc..
```
